---
#
# Configuration du site
# à recopier dans /content/site/config.yaml
#

# TITRE
params:
  title: "VICTOR"
  subtitle: "Guide d'utilisation"
  # l'image arrondie
  avatar: "/site/media/victor-help.png"
  # l'icône dans l'onglet du navigateur
  favicon: "/site/media/victor-help.png"
  # l'image d'arrière plan
  backgroundImage: "/site/media/geometric.jpg"

# Les menus que l'on peut ajouter
menu:
#  links: # menu qui va apparaître en bas de la carte du sommaire
#  - name: "Documentation Beedream"
#    url: "https://beedream.billerot.eu"
#    weight: 10 # pour trier le menu

  navigation: # menu liens en haut du site 
  - name: "Documentation sur le thème BeeDream"
    url: "https://beedream.billerot.eu/"
    weight: 10
    pre: "help" # nom de l'icône de la bibliothèque des icônes
  - name: "Bibliothèque des icônes"
    url: "https://fontawesome.com/icons?d=gallery&p=2&m=free"
    weight: 20 # pour trier le menu
    pre: "font awesome" # nom de l'icône de la bibliothèque des icônes

---