#
# Configuration du site
# lien symbolyque /config/-default/config.yaml
#
baseURL: "/"
params:
  title: "VICTOR"
  subtitle: "Guide d'utilisation"
  # l'image arrondie
  avatar: "/media/victor-help.png"
  # l'icône dans l'onglet du navigateur
  favicon: "/media/victor-help.png"
  # l'image d'arrière plan
  backgroundImage: "/media/geometric.jpg"
  enableSearch: false

# Les menus que l'on peut ajouter
menu:
#  links: # menu qui va apparaître en bas de la carte du sommaire
#  - name: "Documentation Beedream"
#    url: "https://beedream.billerot.eu"
#    weight: 10 # pour trier le menu

  navigation: # menu liens en haut du site 
  - name: "Documentation sur le thème BeeDream"
    url: "https://beedream.billerot.eu/"
    weight: 10
    pre: "help" # nom de l'icône de la bibliothèque des icônes
  - name: "Bibliothèque des icônes"
    url: "https://semantic-ui.com/elements/icon.html"
    weight: 20 # pour trier le menu
    pre: "font awesome" # nom de l'icône de la bibliothèque des icônes
  - name: "Documentation Hugo"
    url: "https://gohugo.io/"
    weight: 30 # pour trier le menu
    pre: "hospital symbol" # nom de l'icône de la bibliothèque des icône  

# Paramètres indépendant du site
theme: "beedream"
languageCode: "fr-FR"
outputs:
  home: ["HTML", "RSS", "JSON"]
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: friendly # monokai dracula friendly
